name: WhitelistCheck
version: 1.3
api-version: 1.20
main: WhitelistCheck
description: Automatically bans players attempting to join the server if they are not on the whitelist.
author: 4rft5
commands:
  wc:
    description: Manage WhitelistCheck plugin
    usage: /wc <help | reload | disable>
    permission: whitelistcheck.use
    permission-message: You do not have permission to use this command.

permissions:
  whitelistcheck.use:
    description: Allows use of the WhitelistCheck commands
    default: op